core/urls.py
# -*- encoding: utf-8 -*-
"""
Copyright (c) 2019 - present AppSeed.us
"""

from django.contrib import admin
from django.urls import path, include  # add this

urlpatterns = [
    path('admin/', admin.site.urls),          # Django admin route
    path("", include("apps.authentication.urls")), # Auth routes - login / register

    # ADD NEW Routes HERE

    # Leave `Home.Urls` as last the last line
    path("", include("apps.home.urls"))
]

apps/home/forms.py
from django import forms
from .models import Actividad, Encuentro
from django.utils.translation import gettext_lazy as _
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Fieldset, Submit, Div, Field, Column, ButtonHolder, HTML

class ActividadForm(forms.ModelForm):
    class Meta:
        model = Actividad
        fields = '__all__'
        
class ActividadCreacionForm(forms.ModelForm):
    class Meta:
        model = Actividad
        fields = ['nombre']
    
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        self.fields["nombre"].widget.attrs["class"] = "form-control"    
        
class ActividadEdicionForm(forms.ModelForm):
    class Meta:
        model = Actividad
        fields = ['nombre']
    
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        self.fields["nombre"].widget.attrs["class"] = "form-control"    
        
        
class EncuentroCreacionForm(forms.ModelForm):
    fecha = forms.DateField(
        input_formats=['%d/%m/%Y'], 
        widget=forms.DateInput(format='%d/%m/%Y')
    )
    
    hora = forms.TimeField(
        input_formats=['%H:%M'], 
        widget=forms.TimeInput(format='%H:%M')
    )
    
    class Meta:
        model = Encuentro
        fields = ["descripcion", "actividad", "lugar", "fecha", "hora"]
        labels = {
            'descripcion': _('Descripción'),
        }
        
    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        

        for key, value in self.fields.items():
            value.widget.attrs["class"] = "form-control"  
            
        self.fields["fecha"].widget.attrs["class"] = "datepicker form-control"   
        self.fields["hora"].widget.attrs["class"] = "timepicker form-control"   
        
        self.helper = FormHelper()
        self.helper.layout = Layout(
            Column(
                Field('descripcion', wrapper_class='col-md-6 col-sm-12'),
                Field('actividad', wrapper_class='col-md-6 col-sm-12'),  
            css_class='row'), 
            Column(
                Field('lugar', wrapper_class='col-md-6 col-sm-12'),
                Field('fecha', wrapper_class='col-md-6 col-sm-12'),  
            css_class='row'),
            Column(
                Field('hora', wrapper_class='col-md-6 col-sm-12'),
            css_class='row'),
            ButtonHolder(
                Submit('submit_guardar', 'Guardar', css_class='btn btn-primary'),
                HTML('<button name="submit_cancelar" formnovalidate  class="btn btn-secondary">Cancelar</button>')
            )
        )

apps/templates/base/actividad_eliminar.html
{% extends "layouts/base.html" %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div>
    <div class="py-4">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Actividad</li>
            </ol>
        </nav>

        <div class="d-flex justify-content-between w-100 flex-wrap">
            <div class="mb-3 mb-lg-0">
                <h1 class="h4">Actividad</h1>
                <p class="mb-0">Eliminar la actividad {{ obj.id}}.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-4">
            <div class="card border-0 shadow components-section">
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <p> Esta seguro que desea eliminar la actividad: {{ obj }}</p>
                        <a href="{{request.META.HTTP_REFERER}}">Volver</a>
                        <div class="mb-3">
                            <button type="submit" class="btn btn-danger">Eliminar</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/base/actividad_form.html
{% extends "layouts/base.html" %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div>
    <div class="py-4">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <!-- <li class="breadcrumb-item"><a href="#">Volt</a></li> -->
                <li class="breadcrumb-item active" aria-current="page">Actividad</li>
            </ol>
        </nav>

        <div class="d-flex justify-content-between w-100 flex-wrap">
            <div class="mb-3 mb-lg-0">
                <h1 class="h4">Actividad</h1>
                <p class="mb-0">Crear una nueva Actividad.</p>
            </div>
            <!-- <div>
                <a href="https://themesberg.com/docs/volt-bootstrap-5-dashboard/components-forms/"
                    class="btn btn-outline-gray"><i class="far fa-question-circle me-1"></i> Forms Docs</a>
            </div> -->
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-4">
            <div class="card border-0 shadow components-section">
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        {% for field in form.visible_fields %}
                        <div class="mb-3">
                            {{ field.label_tag }} {{ field }}
                        </div>
                        {% endfor %}
                        <div class="mb-3">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                            <a href="{{request.META.HTTP_REFERER}}"><button class="btn btn-secondary">Volver</button></a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/base/actividad_lista.html
{% extends "layouts/base.html" %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

<div>
    <div class="py-4">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <!-- <li class="breadcrumb-item"><a href="#">Volt</a></li> -->
                <li class="breadcrumb-item active" aria-current="page">Actividades</li>
            </ol>
        </nav>

        <div class="d-flex justify-content-between w-100 flex-wrap">
            <div class="mb-3 mb-lg-0">
                <h1 class="h4">Actividades</h1>
                <p class="mb-0">Listado de Actividades.</p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12 mb-4">
            <div class="card border-0 shadow components-section">
                <div class="card-body">
                    <table class="table table-centered table-nowrap mb-0 rounded">
                        <thead class="thead-light">
                            <tr>
                                <th class="border-0 rounded-start">Id</th>
                                <!-- <th class="border-0">Nombre</th> -->
                                <th class="border-0 rounded-end">Nombre</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for actividad in actividades %}
                            <tr>
                               <td><a href="#" class="text-primary fw-bold">{{ actividad.id }} </a> </td>
                               <td><a href="{% url 'actualizar-actividad' actividad.id %}"> {{ actividad.nombre }}  </a> </td>
                            </tr>
                           
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

apps/templates/base/encuentro_form.html
{% extends "layouts/base.html" %}

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <!-- jQuery -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

  <!-- XDSoft DateTimePicker -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>

<div>
    <div class="py-4">
        <nav aria-label="breadcrumb" class="d-none d-md-inline-block">
            <ol class="breadcrumb breadcrumb-dark breadcrumb-transparent">
                <li class="breadcrumb-item">
                    <a href="#">
                        <svg class="icon icon-xxs" fill="none" stroke="currentColor" viewBox="0 0 24 24"
                            xmlns="http://www.w3.org/2000/svg">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                                d="M3 12l2-2m0 0l7-7 7 7M5 10v10a1 1 0 001 1h3m10-11l2 2m-2-2v10a1 1 0 01-1 1h-3m-6 0a1 1 0 001-1v-4a1 1 0 011-1h2a1 1 0 011 1v4a1 1 0 001 1m-6 0h6">
                            </path>
                        </svg>
                    </a>
                </li>
                <!-- <li class="breadcrumb-item"><a href="#">Volt</a></li> -->
                <li class="breadcrumb-item active" aria-current="page">Encuentro</li>
            </ol>
        </nav>

        <div class="d-flex justify-content-between w-100 flex-wrap">
            <div class="mb-3 mb-lg-0">
                <h1 class="h4">Encuentro</h1>
                <p class="mb-0">Crear un nuevo encuentro.</p>
            </div>
            <div>
                <a href="{{request.META.HTTP_REFERER}}"
                    class="btn btn-outline-gray"><i class="far fa-question-circle me-1"></i> Volver </a>
            </div>
        </div>
    </div>
    {% load crispy_forms_tags %}

    <div class="row">
        <div class="col-12 mb-4">
            <div class="card border-0 shadow components-section">
                <div class="card-body">
                    <form method="POST" action="">
                        {% csrf_token %}
                        <!-- {% for field in form.visible_fields %}
                        <div class="mb-3">
                            {{ field.label_tag }} {{ field }}
                        </div>
                        {% endfor %} -->
                        <!-- {{ form|crispy }} -->
                        {% crispy form %}
                        <!-- <div class="mb-3">
                            <button type="submit" class="btn btn-primary">Guardar</button>
                            
                        </div> -->
                        <!-- <a href="{{request.META.HTTP_REFERER}}"><button class="btn btn-secondary">Volver</button></a> -->
                    </form>
                    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}
<script>

    
   $(function () {
      $.datetimepicker.setLocale('es');
      $("#id_fecha").datetimepicker({
        timepicker:false,
        format:'d/m/Y'
      });

      $("#id_hora").datetimepicker({
        datepicker:false,
        format:'H:i'
      });
    });
</script>
{% endblock javascripts %}